# internal services
actual-budget.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
beta.ym-pdf:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
bitwarden.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
collabora-online.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
couchdb.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
cv-redirect:
  ttl: 300
  type: A
  value: 168.119.172.112
do-vm:
  ttl: 300
  type: A
  value: 146.190.206.52
fileshare:
  ttl: 300
  type: A
  value: 168.119.172.112
freshrss.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
grafana.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
home.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
id.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
jellyfin.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
modded-mc:
  ttl: 300
  type: CNAME
  value: do-vm.alper-celik.dev.
nextcloud.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
pgadmin.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
music.lab:
  ttl: 300
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.
documents.lab:
  type: CNAME
  value: rpi5.tailnet.alper-celik.dev.

  # hetzner-server-1
adguardhome.lab:
  type: CNAME
  value: hetzner-server-1.tailnet.alper-celik.dev.

  # Github pages:
ym-pdf:
  ttl: 300
  type: CNAME
  value: alper-celik.github.io.
blog:
  ttl: 300
  type: CNAME
  value: alper-celik.github.io.

  # "public" services:
photos.lab:
  ttl: 300
  type: CNAME
  value: rpi5.devices.alper-celik.dev.

  # Devices:
rpi5.devices:
  ttl: 300
  type: CNAME
  value: rpi5.ddns.alper-celik.dev.
rpi5.tailnet:
  ttl: 300
  type: A
  value: 100.104.52.23
hetzner-server-1.tailnet:
  type: A
  value: 100.81.156.90
hetzner-server-1.devices:
  ttl: 300
  type: A
  value: 168.119.172.112
