name: auto deployment

on:
  push:
    branches: ["main"]

  workflow_run:
    workflows: ["Update DNS"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do  cancel in-progress runs as we probably deployed older commits localy so we shouldn't rollback to old versions when we push
concurrency:
  group: "deployment"
  cancel-in-progress: true

jobs:
  updateDns-build-deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        background: true
        with:
          tool-cache: true

      - name: Tailscale
        id: tailscale
        uses: tailscale/github-action@v2
        background: true
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Checkout
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.10.5
        with:
          extra_nix_config: |
            keep-env-derivations = true
            keep-outputs = true
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        id: nixcache
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 5G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or last accessed this duration (ISO 8601 duration format)
          # before the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: P1DT12H
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never

      - name: update dns
        run: ./dns/update-dns.sh --doit
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - wait: tailscale

      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo  "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # ssh-keyscan rpi5.tailnet.alper-celik.dev > ~/.ssh/known_hosts
          ssh-keyscan hetzner-server-1.devices.alper-celik.dev >> ~/.ssh/known_hosts
          ssh-keyscan api.projectread.ing >> ~/.ssh/known_hosts
          # ssh-keyscan 172.25.42.61 >> ~/.ssh/known_hosts
          # ssh-keyscan network-vm > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: build/check
        run: nix flake check -L

      - name: deploy
        run: ./deploy.sh
